import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Layout/Header";
import Footer from "@/Components/Layout/Footer";
import WhatsAppButton from "@/Components/Layout/FloatingWhatsapp";
import ScrollButton from "@/Components/Layout/ScrollToTop";
import CallButton from "@/Components/Layout/CallButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col">
        <Header />
        <CallButton />
        <WhatsAppButton />
        <ScrollButton />
        <main className="min-h-screen  overflow-x-hidden pt-22">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
